### ISSUE TITLE
Image order and timing issues

### ISSUE THREAD

**Issue by kgoldmann** [kush-agra/Dynamic_Walls#5]
First of all, the wallpaper files seem to be sorted and numbered in the wrong order. If you follow the light and the shadows on the dune, this is easy to spot. I believe the correct order is:

- 002 (dawn)
- 003 (sunrise)
- 004 (daybreak) 
- 005
- 006
- 007
- 008 (noon)
- 009
- 010
- 011
- **001**
- 012 (sunset)
- 013 (dusk)
- 016 (nightfall)
- **015**
- **014**

I'm not sure if you've already noticed this and compensate by not displaying the images in their numbered order, but the script's display order is currently inconsistent to both the numbering and the actual order. For example, 008 appears after 009, 009 then repeats after 008 and 013 appears after 011 (my location: Berlin; 24h time).

I have also noticed that the timing of the changes does not correspond well to moments like sunset, sunrise, dusk, dawn, and the time periods are quite unevenly spaced. For example: 013 appears over 5.5 hours after the previous image, while other periods are much shorter, and 014 appears long after nightfall.

Many thanks for creating and updating this script!

**Comment by kush-agra** [comment]
I thought the order was correct, I'm not using 001 at all, I believe that is the default wallpaper when dynamic wallpaper feature is off on mojave

rest of the images I assumed to be in order as extracted from mojave beta

013 is when the sun is going down on the left
014 is when the sun has gone further down and the moon starts to appear from the right
015 is when the sun is completely gone and the moon is higher above illuminating the entire ground instead of just one side
016 is when the moon has moved towards the left and is illuminating just the left side of the dune

the 008 appearing after 009 etc does seem like an issue it wasn't intended I'll have a look thank you :)

and the periods are irregular because we have only 5 images after sunset compared to 10 images during the day time but 13 is supposed to appear around 30 minutes after sunset so that seems to be an issue as well I'll try fixing it 😇

do you agree with the naming being in the correct order? or should I change that too, I preferred that one because that's the order that was extracted automatically from the mojave beta

**Comment by kgoldmann** [comment]
I think the order extracted is wrong then, might be a bug on Apple's side. This is an animation of the order I suggested (including 001, I think it's the fallback, but still a part of the sequence):

![output_iam2qm](https://user-images.githubusercontent.com/8964638/41296814-0a71da0c-6e5e-11e8-882f-5d1080739148.gif)

Looks seemless and logical to me, what do you think?

It makes perfect sense that not all periods are the same – night has fewer images than day, and the periods between sunrise & dawn and sunset & dusk are predetermined. But within day and night, they should be at least more evenly spaced out, if possible, i.e. not 1h-1h-5h. 😉

**Comment by kush-agra** [comment]
That does seem logical I'll change it to that and agreed it wasn't even supposed to be 5 hours it was supposed to be 1 hour 36 minutes or something close to that, checking it right now to see what is up with that, I do have the solar noon time, I averaged a few places around the globe and it came to be 12:06 pm so I just used 12pm as solar noon instead

**Comment by kush-agra** [comment]
try [this](https://www.dropbox.com/s/bktxr6dw2bkkzm6/Dynamic_Walls.scpt?dl=0) I tested it out by manually plugging in Berley,Ney Jersey's values and couldn't see the 008 appearing after 009 bug

let me know if that fixes it :)

**Comment by Dniel97** [comment]
That seems to fix the problem just fine 👍

**Comment by kush-agra** [comment]
😌 Thanks, also changed the image order 😬, thank you for that
